name: 'The Dragon Code Styler'
description: 'A tool to automatically fix PHP Coding Standards issues by Dragon Code.'
author: 'Andrey Helldar'

inputs:
    fix:
        description: 'Only shows which files would have been modified.'
        required: false
        default: 'false'
    github_token:
        description: 'GitHub token or PAT token.'
        required: false
        default: ${{ github.token }}

runs:
    using: docker
    image: Dockerfile
    args:
        - ${{ inputs.fix }}
        - ${{ inputs.github_token }}

branding:
    icon: check
    color: purple
