name: 'The Dragon Code Styler'
description: 'A tool to automatically fix PHP Coding Standards issues by Dragon Code.'

inputs:
    path:
        description: 'Specifies one or more paths to test.'
        required: false
        default: 'src tests'
    fix:
        description: 'Only shows which files would have been modified.'
        required: false
        default: 'false'

runs:
    using: docker
    image: Dockerfile
    args:
        - ${{ inputs.path }}
        - ${{ inputs.fix }}

branding:
    icon: check
    color: purple
