name: 'The Dragon Code Styler'
description: 'A tool to automatically fix PHP Coding Standards issues by The Dragon Code.'
author: 'Andrey Helldar'
inputs:
    github_token:
        description: 'GitHub token or PAT token.'
        required: false
        default: '${{ github.token }}'
    fix:
        description: 'Only shows which files would have been modified.'
        required: false
        default: 'false'
    editorconfig:
        description: 'Update .editorconfig file.'
        required: false
        default: 'true'
    dependabot:
        description: 'Update Dependabot rules.'
        required: false
        default: 'true'
    normalize:
        description: 'Normalize the composer.json file.'
        required: false
        default: 'true'
    verbose:
        description: 'Increase the verbosity of messages for debug'
        required: false
        default: 'false'
runs:
    using: docker
    image: Dockerfile
    args:
        - '${{ inputs.github_token }}'
        - '${{ inputs.fix }}'
        - '${{ inputs.editorconfig }}'
        - '${{ inputs.dependabot }}'
        - '${{ inputs.normalize }}'
        - '${{ inputs.verbose }}'
branding:
    icon: check
    color: purple

