name: Code Style Development

on:
    workflow_call:

permissions: write-all

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Fix the code style
                uses: ./
                with:
                    fix: true
                    editorconfig: false
