name: Docker

on:
    push:
        tags:
            - v*

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2.4.0

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v3.6.2
                with:
                    images: helldar/codestyler
                    tags: |
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
                        type=semver,pattern={{major}}

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1.2.0

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1.6.0

            -   name: Login to DockerHub
                uses: docker/login-action@v1.12.0
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Build and push
                uses: docker/build-push-action@v2.9.0
                with:
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
