name: phpunit

on: [ push ]

permissions: read-all

jobs:
    build:
        runs-on: ubuntu-latest

        name: PHP Unit

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json
                    coverage: none

            -   name: Install dependencies
                run: composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: sudo vendor/bin/phpunit --colors=always
