name: 'Update Tag Aliases'

on:
    push:
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Get tag name
                if: success()
                id: tag
                run: |
                    VERSION=${GITHUB_REF/refs\/tags\//}

                    echo ::set-output name=major::${VERSION:0:2}

            -   name: Create major tag
                uses: rickstaa/action-create-tag@v1
                with:
                    tag: ${{ steps.tag.outputs.major }}
                    force_push_tag: true

            -   name: Create latest tag
                uses: rickstaa/action-create-tag@v1
                with:
                    tag: latest
                    force_push_tag: true
