name: tests

on: [ push, pull_request ]

permissions: read-all

jobs:
    tests:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: true
            matrix:
                os: [ "ubuntu-latest", "windows-latest" ]
                php: [ "8.1", "8.2" ]

        name: PHP ${{ matrix.php }} - ${{ matrix.os }}

        steps:
            -   name: Set git to use LF
                run: |
                    git config --global core.autocrlf false
                    git config --global core.eol lf

            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json, dom, curl, libxml, fileinfo
                    ini-values: error_reporting=E_ALL
                    coverage: none

            -   name: Install dependencies
                run: composer install --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute lint tests with Laravel preset
                run: ./codestyle check

            -   name: Execute unit/feature tests
                run: sudo ./vendor/bin/pest
