name: Tests

on:
    push:
    pull_request:
    workflow_dispatch:

permissions: read-all

jobs:
    container:
        runs-on: ubuntu-latest

        name: Container

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Check the container
                uses: TheDragonCode/codestyler@3.x

    unit:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: true
            matrix:
                os: [ "ubuntu-latest", "windows-latest" ]
                php: [ "8.1", "8.2" ]

        name: PHP ${{ matrix.php }} - ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
                with:
                    submodules: true

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json, dom, curl, libxml, fileinfo
                    ini-values: error_reporting=E_ALL
                    coverage: none

            -   name: Git setup
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"
                    
                    git config --global core.autocrlf false
                    git config --global core.eol lf

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

            -   name: Execute unit/feature tests
                run: php ./codestyle test --colors=always
