name: update-major-version

run-name: Move ${{ github.event.release.tag_name }} to ${ github.event.release.tag_name:0:2 }

on:
    release:
        types:
            - released
        tags-ignore:
            - v1.*
    workflow_dispatch:
        inputs:
            target:
                description: The tag or reference to use
                required: true
            major_version:
                type: choice
                description: The major version to update
                options:
                    - v3
                    - v2

permissions: write-all

jobs:
    tag:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Git config
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"

            -   name: Get versions
                run: |
                    echo ::set-output name=full_version::${{ github.event.release.tag_name }}
                    echo ::set-output name=major_version::${ github.event.release.tag_name:0:2 }

            -   name: Tag new target
                run: git tag -f ${{ steps.get_version.outputs.major_version }} ${{ steps.get_version.outputs.full_version }}

            -   name: Push new tag
                run: git push origin ${{ steps.get_version.outputs.major_version }} --force
